groups:
- name: main
  jobs:
  - unit-tests
  - build-artifact
  - deploy-app
  - integration-test
  - ship-it
  - patch
  - major
  - minor

resources:
- name: git-assets
  type: git
  source:
    branch: master
    uri: https://github.com/akirasoft/volume-demo.git
- name: Cloudfoundry
  type: cf
  source:
    api: ((cf-api))
    organization: ((cf-org))
    space: ((cf-space))
    username: ((cf-user))
    password: ((cf-pwd))
    skip_cert_check: true
- name: version
  type: semver
  source:
    bucket: acm-workshop-concourse-volume-demo
    key: volume-demo
    access_key_id: ((s3-access-key-id))
    secret_access_key: ((s3-secret-access-key))
- name: pre-release
  type: github-release
  source:
    user: akirasoft
    repository: volume-demo
    access_token: ((github-token))
    pre_release: true
    drafts: true
- name: release
  type: github-release
  source:
    user: akirasoft
    repository: volume-demo
    access_token: ((github-token))

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: git-assets
    trigger: true
  - task: mvn-test
    file: git-assets/ci/tasks/unit-tests.yml

- name: build-artifact
  serial: true
  public: true
  serial_groups: [version]
  plan:
  - get: git-assets
    trigger: true
    passed:
    - unit-tests
  - get: version
    params: {pre: rc}
    trigger: true
  - task: mvn-package
    file: git-assets/ci/tasks/mvn-package.yml
    params:
      CF_APP: ((cf-app-name))
  - put: pre-release
    params:
      name: version/number
      tag: version/number
      globs:
        - volume-demo-releases/volume-demo*.jar
  - put: version
    params:
      file: version/number

- name: deploy-app
  serial: true
  public: true
  serial_groups: [version]
  plan:
  - get: git-assets
    trigger: true
    passed:
    - build-artifact
  - get: pre-release
    trigger: true
    params:
      globs:
        - volume-demo*.jar
    passed:
      - build-artifact
  - get: version
  - task: get-current-app-color
    file: git-assets/ci/tasks/current-app-get-info.yml
    params:
      CF_APP: ((cf-app-name))
      CF_APP_DOMAIN: ((cf-app-domain))
      CF_API: ((cf-api))
      CF_ORG: ((cf-org))
      CF_USER: ((cf-user))
      CF_PWD: ((cf-pwd))
      CF_SPACE: ((cf-space))
  - task: prepare-app-manifest
    file: git-assets/ci/tasks/app-manifest-prep.yml
    params:
      CF_APP: ((cf-app-name))
  - put: Cloudfoundry
    params:
      manifest: ./app-manifest-output/manifest.yml

- name: integration-test
  serial: true
  public: true
  serial_groups: [version]
  plan:
  - get: git-assets
    trigger: true
    passed:
    - deploy-app
  - task: get-current-app-color
    file: git-assets/ci/tasks/current-app-get-info.yml
    params:
      CF_APP: ((cf-app-name))
      CF_APP_DOMAIN: ((cf-app-domain))
      CF_API: ((cf-api))
      CF_ORG: ((cf-org))
      CF_USER: ((cf-user))
      CF_PWD: ((cf-pwd))
      CF_SPACE: ((cf-space))
  - task: int-testing
    file: git-assets/ci/tasks/int-tests.yml
    params:
      CF_APP: ((cf-app-name))
      CF_APP_DOMAIN: ((cf-app-domain))
- name: ship-it
  serial: true
  public: true
  serial_groups: [version]
  plan:
  - get: git-assets
    trigger: true
    passed:
    - integration-test
  - task: get-current-app-color
    file: git-assets/ci/tasks/current-app-get-info.yml
    params:
      CF_APP: ((cf-app-name))
      CF_APP_DOMAIN: ((cf-app-domain))
      CF_API: ((cf-api))
      CF_ORG: ((cf-org))
      CF_USER: ((cf-user))
      CF_PWD: ((cf-pwd))
      CF_SPACE: ((cf-space))
  - get: pre-release
  - get: version
    params:
      bump: final
  - task: create-release
    file: git-assets/ci/tasks/release.yml
    params:
      CF_APP: ((cf-app-name))
  - task: switch-app-routes
    file: git-assets/ci/tasks/update-routes.yml
    params:
      CF_APP: ((cf-app-name))
      CF_APP_DOMAIN: ((cf-app-domain))
      CF_API: ((cf-api))
      CF_ORG: ((cf-org))
      CF_USER: ((cf-user))
      CF_PWD: ((cf-pwd))
      CF_SPACE: ((cf-space))
  - put: release
    params:
      name: version/number
      tag: version/number
      globs:
          - volume-demo-releases/volume-demo*.jar
  - put: version
    params:
      file: version/number
- name: patch
  serial_groups: [version]
  plan:
  - get: version
    passed: [ship-it]
    trigger: true
  - put: version
    params: {bump: patch, pre: rc}
- name: major
  serial_groups: [version]
  plan:
  - put: version
    params: {bump: major, pre: rc}
- name: minor
  serial_groups: [version]
  plan:
  - put: version
    params: {bump: minor, pre: rc}
